name: HTTPS test

on:
  workflow_dispatch:
    inputs:
      runner-tag:
        description: runner to execute on
        required: true
        default: ubuntu-latest
permissions:
  contents: read

jobs:

  https-test:
    runs-on: ${{ inputs.runner-tag }}
    steps:

      - uses: step-security/harden-runner@c51e8eeb6c4fdcd08f65e43a051dacdbfaa69702 # rc
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # main
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # main
        with:
          node-version: 18

      - run: docker pull alpine:latest
    
      - name: do node call
        run: |
          node req.js
      - run: sudo apt update
      
      - run: curl https://api.github.com/meta
